### ISSUE TITLE
Support for Cache-Digest (Server Push optimization)

### ISSUE THREAD

**Issue by optimalisatie** [nodejs/http2#190]
Hi!

It would be nice if the Server Push implementation would support Cache-Digest. It will reduce both latency and bandwidth.

> **PerfPlanet.com** TL;DR Without Cache Digests there is no clear-cut performance win for HTTP/2 Server Push over HTTP/1 Asset Bundling. However, a Bloom filter based technique, called Cache Digests, makes Server Push more efficient than Asset Bundling in both latency and bandwidth. 

![cache-digest](https://user-images.githubusercontent.com/8843669/31587523-8530e7fc-b1e3-11e7-93f1-6d6208c8d5bc.png)

https://calendar.perfplanet.com/2016/cache-digests-http2-server-push/
http://httpwg.org/http-extensions/cache-digest.html
https://jakearchibald.com/2017/h2-push-tougher-than-i-thought/

Cache-Digest is currently a draft for the official HTTP/2 spec. It controls what assets are pushed before they are pushed. It is not a cache layer and not a client side cache. The client will calculate a hash that is processed by the HTTP/2 server. 

http://httpwg.org/http-extensions/cache-digest.html
https://tools.ietf.org/html/draft-ietf-httpbis-cache-digest-02

An example of the client side hash calculation can be found in the following library (a Service Worker that calculates Cache-Digest). It's nicely documented on each step of the calculation.

https://gitlab.com/sebdeckers/cache-digest-immutable

A Service Worker could detect what resources have been pushed so that a Cache Digest could be calculated based on previously pushed resources. This would make management more simple: it will calculate a hash for resources that have been pushed by the HTTP/2 server and that therefor are likely to be relevant, while ignoring the potential thousands of other files. An expire time could further restrict the complexity of the hash calculation so that it could become as efficient as possible. The example in `cache-digest-immutable` does not use those techniques however they have been implemented in a first version of a Google PWA Service Worker that is part of the WordPress plugin Above The Fold Optimization. The source code is available on Github:

https://github.com/optimalisatie/above-the-fold-optimization/blob/master/trunk/public/js/src/pwa.serviceworker.js

The Above The Fold Optimization plugin provides HTTP/2 Server Push optimization based on Cache-Digest. This is the reason that we are interested to help make it available. 

HTTP/2 Server Push + Cache-Digest will be a very big step forward for front end performance optimization.

**Comment by mcollina** [comment]
I think this is better explored in the ecosystem rather than in core. Why should this be in core?

@sebdeckers you worked on those components, do you think it might be worth it to implement them in core?

**Comment by optimalisatie** [comment]
Server Push without Cache-Digest has almost no advantage for performance so it's a incomplete functionality.

> Unfortunately, even with perfect browser support you'll have wasted bandwidth and server I/O before you get the cancel message. Cache digests aim to solve this, by telling the server in-advance what it has cached.
> https://jakearchibald.com/2017/h2-push-tougher-than-i-thought/

Users may be misguided by the promise of HTTP/2 while Server Push without a Cache Digest will degrade performance on some aspects.

When Cache-Digest is available in the core the ecosystem can use it as a best practice and achieve optimal performance for their HTTP/2 server.

**Comment by apapirovski** [comment]
I think that cache digest sent using frames should be in core, if it becomes a part of the spec. But I don't see why the core should implement support for cache digests as headers, that's definitely a user-land concern. We don't really process other headers and we should follow the same pattern here.

For this to be supported we would probably want nghttp2 to finalize their implementation: https://github.com/nghttp2/nghttp2/issues/587 (or we can use the ability to add custom frames ourseleves)

**Comment by apapirovski** [comment]
Also, the fact that all client-side implementations of this (via headers) are in user-land rather than in the browsers, strongly indicates that this is not something that should be a part of Node core either.

**Comment by optimalisatie** [comment]
The requirement of a service worker indicates that it would normally be part of the browser instead of user-land. It's a hack that enhances the browsers network handling to instruct the HTTP/2 server to optimize server push (i.e. not waste precious IO and bandwidth resources).

The browser doesn't know anything of the context of the resources of a website so it can't efficiently calculate a cache digest or instruct the HTTP/2 server. This may be why control lays with the user. 

The optimization itself lays within the HTTP/2 server. It will need to efficiently decide what resources to push for potentially 100,000 active clients, a potential difference of 50 GB per 100,000 requests.

**Comment by sebdeckers** [comment]
@optimalisatie Thanks for sharing! Love the work you are doing with above-the-fold. 👍 I am also very passionate about this particular spec.

IMHO it is too early to implement cache digests in Node.js Core or any production software. It is an experimental RFC after all. Hopefully we will get there soon, but there is more work to be done on the spec.

For Node.js, exposing a generic way to send and receive custom frames at the JS layer would be great. This was proposed and deferred before, see https://github.com/nodejs/http2/issues/146, but perhaps can now be reconsidered. Interested?

As it happens I am currently at IETF100 and spent the last few days:
1. learning about the IETF process, as this is my first time attending;
1. talking to people from the HTTP Working Group about Cache Digest and other things;
1. at the hackathon, working (with amazing guidance from @kazuho) on a prototype of the modified cache digests spec proposed by @yoavweiss that would use cuckoo filters;

Some things I learned so far:
- The cache digest spec may be briefly presented on Friday, though I don't know if there will be time for discussion (anyone can [follow the meeting remotely](https://datatracker.ietf.org/meeting/100/agenda.html) (see Friday morning));
- Using cuckoo filters would be great for browsers so they do not need to iterate through their entire cache as they can remove items from the digest when their are purged from the local browser cache;
- It is currently an open question whether cuckoo filters would require too much size overhead compared with golomb coded sets;
- The very clever implementation based on cookies ([CASPer](https://h2o.examp1e.net/configure/http2_directives.html#http2-casper)) was prototype presented at an earlier IETF meeting. It led to the current experimental RFC;
- The intent of server push (and CD) seems to be about avoiding wasted RTT by filling the initial request, not so much about replacing the frontend practice of JS/CSS/etc concatenation (which is what I personally was interested in);
- (aside) Implementation of cache digest in Firefox might require significant work on the caching implementation since it currently would require iterating through the global cache.

My WIP cuckoo filter cache digest prototype is at:
https://gitlab.com/http2/cache-digest-koel

Yoav Weiss is reportedly also working on an implementation:
https://twitter.com/yoavweiss/status/930012306997641216

**Comment by sebdeckers** [comment]
BTW @optimalisatie you can test my above-mentioned service worker implementation against the server support in https://www.npmjs.com/package/@http2/server (or the public https://http2.live service which is the same server).

**Comment by optimalisatie** [comment]
Hi @sebdeckers,

Thank you for the valuable information!

> The intent of server push (and CD) seems to be about avoiding wasted RTT by filling the initial request, not so much about replacing the frontend practice of JS/CSS/etc concatenation (which is what I personally was interested in);

This is also what I am interested in. I've tested alternative solutions such as HTML5 [Streams API](https://developer.mozilla.org/en-US/docs/Web/API/Streams_API) to load individual files in a single request, however, when HTTP/2 would be enhanced with Cache-Digest then it will most likely be the best solution. FPO is currently simply waiting for the HTTP/2 spec in order to enhance performance on that level.

Hopefully a solution will become available soon. I will be watching your projects!

Have a great time at IETF100!

**Comment by apapirovski** [comment]
Suggestions was discussed and nothing actionable is available at this moment. Future issues would be better off in https://github.com/nodejs/node

Feel free to re-open if you think this should still be open though! :)

**Comment by optimalisatie** [comment]
Thank you for considering. 

While off topic, the following may be of interest to readers of this topic.

We recently implemented a Service Worker based asset push system that enables to push assets to the client when not already available in the cache. It uses a custom header, e.g. `X-SW-PRELOAD` that contains the assets attached to a page (for example all thumbnails of a product index). The Service Worker will be able to process that header on a request. Some options are downloading assets, optimizing and in-lining them in the page HTML or simply to start a Fetch request while the page HTML is being sent enabling the images to be served from cache or to hook into an already running fetch request.

The solution is available for testing in our Service Worker optimization plugin for WordPress.

https://github.com/o10n-x/wordpress-pwa-optimization
