### ISSUE TITLE
http2: status of push API

### ISSUE THREAD

**Issue by mcollina** [nodejs/http2#67]
placeholder from the collab summit in Berlin

**Comment by robertkowalski** [comment]
Question: Do we want to support legacy APIs?

`test-http-set-cookies.js` uses a currently **not** documented way to set headers (note the nested array instead of a flat object):

```js
    res.writeHead(200, [['set-cookie', 'A'],
                        ['set-cookie', 'B'],
                        ['content-type', 'text/plain']]);
```

I'm in favor of just supporting objects. However I remember somehow from this morning that the goal is to support as much of the old behaviour as possible. What do you think @nodejs/http2 ?

**Comment by mcollina** [comment]
@robertkowalski I'd focus on documented behavior.

**Comment by jasnell** [comment]
For now, definitely focus on documented behavior. We can revisit this once we have that done and working.

**Comment by sebdeckers** [comment]
🤔 Is this issue discussing server push support or header API compatibility?

The compatibility layer in #47 tries to stay true to the *documented* APIs, for headers on the request and response. Cookies are not yet supported. I don't think it's prohibitively difficult but would rather leave it for a separate PR.

FWIW, core currently uses an Object for headers and trailers. That could be changed to using a Map or linked list.

**Comment by mcollina** [comment]
I think we can close this now.
