### ISSUE TITLE
engaging with the maintainer of http2 on npm

### ISSUE THREAD

**Issue by mcollina** [nodejs/http2#7]
@nwgh @molnarg - we are in the process of adding support of HTTP2 to core, using nghttp2.

I think any point of view you have on the APIs, the challenges, etc, will be highly welcome.

**Comment by ronkorving** [comment]
I would then like to poke @indutny for the same reason (https://www.npmjs.com/package/spdy)

**Comment by nwgh** [comment]
Hi @mcollina (and others working on this). First of all, a big :thumbsup: for this effort - it will be great to have a robust, high-performance h2 implementation in node core.

For me, the biggest challenge (that will be relevant to the node-native implementation) is how and what error states to expose versus performing automatic fallbacks/retries/etc.

One example of this is receiving the error code HTTP_1_1_REQUIRED. Should the library automatically dial back with HTTP/1.1, let the caller handle that, or should it be configurable? Similar issues exist around other error codes.

Another issue that node-http2 has struggled with (from the point of view of its users) is how strict/lenient to be with input from the API that may not jive with what the spec requires - https://github.com/molnarg/node-http2/issues/158 is the issue I'm thinking of. So far, I've leaned towards being very strict (as you can see in the issue) - this is probably due to my bias in using node-http2 as a platform for testing Firefox's h2 stack :)

In terms of the API - node-http2 has tried to stick to core's http API as closely as possible. We have some gaps (both known and unknown), but for at least basic use cases I think we have parity.

Really, my biggest problem with node-http2 has been lack of time to spend on fixing clear-cut bugs and increasing API parity with core :)

Let me know if you need/want any more info from me, I'm more than happy to help discuss as my time allows.

**Comment by mcollina** [comment]
thanks for your very long response! we'll let you know if there are more questions!
